name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/2048-game:${{ github.run_id }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/2048-game:${{ github.run_id }}|" kubernetes/deployment.yaml

      - name: Commit and push updated deployment.yaml
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "sijomt"
          git config user.email "sijomthomas05@gmail.com"
          git add kubernetes/deployment.yaml
          git commit -m "[CI]: Update image tag"
          git push origin HEAD:master -f
